#!/usr/bin/env python3
"""Scans image directories and generates images/manifest.js.

Run from the repository root whenever images are added, removed, or renamed:
    python3 generate-manifest.py
"""

import json
import os
import sys

IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.gif', '.svg'}
DIRECTORIES = ['hero', 'featured', 'cards']
IMAGES_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'images')
OUTPUT_FILE = os.path.join(IMAGES_ROOT, 'manifest.js')


def get_images(directory):
    path = os.path.join(IMAGES_ROOT, directory)
    if not os.path.isdir(path):
        return []
    files = [
        f for f in os.listdir(path)
        if os.path.splitext(f)[1].lower() in IMAGE_EXTS
    ]
    files.sort()
    return files


def main():
    manifest = {d: get_images(d) for d in DIRECTORIES}

    js_content = (
        '// Auto-generated by generate-manifest.py — do not edit manually\n'
        'window.IMAGE_MANIFEST = '
        + json.dumps(manifest, indent=2)
        + ';\n'
    )

    with open(OUTPUT_FILE, 'w') as f:
        f.write(js_content)

    for d in DIRECTORIES:
        print(f'  {d}/: {len(manifest[d])} image(s)')
    print(f'Wrote {OUTPUT_FILE}')


if __name__ == '__main__':
    main()
