// Auto-generated by generate-manifest.py — do not edit manually
window.IMAGE_MANIFEST = {
  "hero": [
    "01_Website_Title_Pgs_SS3_Perspective.png",
    "02_Website_Title_Pgs_SS2_Expression.png",
    "03_Website_Title_Pgs_SS1_RTR_X_Stitched_Up.png",
    "04_Website_Title_Pgs_SS5_Stitched_Up.png",
    "05_Website_Title_Pgs_SS4_Strange_Beauty.png",
    "06_Website_Title_Pgs_SS6_Renaissance_Romance.png"
  ],
  "featured": [
    "01.png",
    "02.png",
    "03.png",
    "04.png"
  ],
  "cards": [
    "01_Website_Title_Pgs_SS2_Expression.png",
    "02_Website_Title_Pgs_SS1_RTR_X_Stitched_Up.png",
    "03_Website_Title_Pgs_SS5_Stitched_Up.png",
    "04_Website_Title_Pgs_SS4_Strange_Beauty.png"
  ]
};
